### ISSUE TITLE
Dark Keyboard Usage

### ISSUE THREAD

**Issue by calebnance** [SKempin/Lyrics-King-React-Native#1]
Hey hey!
Love this project, wanted to suggest using: `keyboardAppearance="dark"` on `<TextInput />`, [docs here](https://facebook.github.io/react-native/docs/textinput.html#keyboardappearance).

https://github.com/SKempin/Lyrics-King-React-Native/blob/f74477fe92863377fdd14f239af1355375d50f12/screens/SearchScreen.js#L111

**Comment by SKempin** [comment]
Thanks, please feel free to make a pull request for this
