### ISSUE TITLE
Expo SDK upgrade required from v32.0.0 to v33.0.0

### ISSUE THREAD

**Issue by sanjeevyadavIT** [SKempin/Lyrics-King-React-Native#7]
Hi, I'm using latest version of expo client on my Android Mobile, and when I tried scanning the QR code to run the app it showed the following error

![Screenshot_20191008-222058_Expo](https://user-images.githubusercontent.com/13250741/66416057-a5030a80-ea1a-11e9-821a-7a96dfeaed25.jpg)
![Screenshot_20191008-222134_Expo](https://user-images.githubusercontent.com/13250741/66416060-a59ba100-ea1a-11e9-8689-12040dfa9cfb.jpg)

The details of expo App that I use in my phone 
```
Client version: 2.13.0
Supported SDKs: 33,34,35
```

Looks like the expo app 2.13.0 only supports expos sdk version above 33

**Comment by sanjeevyadavIT** [comment]
Are you accepting contribution to this project?

**Comment by SKempin** [comment]
@alexakasanjeev Yes I am, please feel free to open a PR with an update to the latest SDK :)

**Comment by sanjeevyadavIT** [comment]
Ok, sure I would work on this, will create a PR, containing upgrade

**Comment by kartik-budhiraja** [comment]
@alexakasanjeev are you working on this issue, if not I would love to take over.

**Comment by sanjeevyadavIT** [comment]
@kartik-budhiraja go ahead take it :smile: 

and if you care checkout https://github.com/alexakasanjeev/magento_react_native there's lot to contribute there

**Comment by Lokeshc123** [comment]
@sanjeevyadavIT  are you still maintaining this repo as the issue is still listed?
